### ISSUE TITLE
为啥我修改了下，背景和下拉菜单都不显示了呢？

### ISSUE THREAD

**Issue by qidouhai** [Dreamer-Paul/KStart#11]

**Comment by Dreamer-Paul** [comment]
无法复现，请提供详细复现步骤，并且请提供截图

**Comment by qidouhai** [comment]
http://www.qwang.cn/

**Comment by Dreamer-Paul** [comment]
错误在控制台打的很清楚了，自行修改 https://github.com/Dreamer-Paul/KStart/blob/master/static/main.js#L120 与本项目链接无关请不要在此继续提问
