### ISSUE TITLE
在site.json添加网站遇到的问题

### ISSUE THREAD

**Issue by yubius** [Dreamer-Paul/KStart#13]
Paul你好，我尝试添加4399小游戏的网站
![image](https://github.com/Dreamer-Paul/KStart/assets/79253940/efbba07e-004c-4419-bfac-8bbc8f0d8bf2)
```
  {
    "name": "4399",
    "url": "https://4399.com",
    "color": "bfe193",
    "icon": "iconfont icon-4399游戏网"
  }
```
但是发现无法显示图标，图标名不能有中文吗？我可以怎么做？

**Comment by Dreamer-Paul** [comment]
是的，不能有中文名
